BookStore Milestone 5
necmigunduz/bookstore-amit-necmi pull request #5
Opened 2021-07-16 14:53 UTC by necmigunduz

In this project, we did;
- Add style to the App.

2021-07-16 15:54 UTC, mahmoud717 requested changes
### Changes required ♻️ 

**Hello @necmigunduz  & @KumarAmitt**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] When I try to create a new book, the category doesn't get appended to the book, and a console error is thrown. Please make sure to fix that.
- [ ] Please make sure to add validation to your form so the user can't create empty books. you can do this by adding required attributes to your form inputs.


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

2021-07-16 19:05 UTC, bellom requested changes
## Hi @necmigunduz   :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

# Status: Changes Required! ♻️ 

Oops, I think you created a bug while working on the changes from the previous reviewer, checkout the videocast below from your app;
![bookstore](https://user-images.githubusercontent.com/31897434/125996602-6851bbc0-7ff3-439b-a9b0-d629c1f1cb3e.gif)

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

2021-07-17 08:30 UTC, Elbie-em requested changes
## STATUS: CHANGES REQUIRED 🟡  ♻️ 

Hi @team, you have done a remarkable job implementing the changes requested. One small fix before this milestone is approved. Check my comments below ⬇️ 

*All the best and keep up the good work* 💪 

> Elbie Moonga (Part-time TSE)

> Github (@Elbie-em)
> Slack (Elbie Moonga)
> Twitter ([@ElbieEm](https://twitter.com/ElbieEm))
> LinkedIn([Elbie Moonga](https://www.linkedin.com/in/elbiemoonga/))

2021-07-17 08:30 UTC, Elbie-em commented on src/components/header.js
> +            <span className="CATEGORIES">CATEGORIES</span>
- [ ] Kindly add your category filter after its label so that users are enabled to filter books

2021-07-17 08:30 UTC, Elbie-em commented on src/components/Book.js
> +        </div>
### [OPTIONAL]

- [ ] This progress score can be a random number between 1 - 100 generated from Math.random()

2021-07-17 12:20 UTC, voscarmv approved these changes
# Project status: Approved 💯 ✨ 😎 👍 
### You may merge this branch and move forward ⛙🛣️ 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

2021-07-19 08:56 UTC, merged